/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashitecnologyRouteRouteImport } from './routes/dashitecnology/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashitecnologyIndexRouteImport } from './routes/dashitecnology/index'
import { Route as DashitecnologyWallpapersRouteImport } from './routes/dashitecnology/wallpapers'
import { Route as DashitecnologyUsersRouteImport } from './routes/dashitecnology/users'
import { Route as DashitecnologyTokensRouteImport } from './routes/dashitecnology/tokens'
import { Route as DashitecnologyTelegramRouteImport } from './routes/dashitecnology/telegram'
import { Route as DashitecnologySystemRouteImport } from './routes/dashitecnology/system'
import { Route as DashitecnologyNotificationsRouteImport } from './routes/dashitecnology/notifications'
import { Route as DashitecnologyMlRouteImport } from './routes/dashitecnology/ml'
import { Route as DashitecnologyMaintenanceRouteImport } from './routes/dashitecnology/maintenance'
import { Route as DashitecnologyLevelsRouteImport } from './routes/dashitecnology/levels'
import { Route as DashitecnologyJobsRouteImport } from './routes/dashitecnology/jobs'
import { Route as DashitecnologyHabitsRouteImport } from './routes/dashitecnology/habits'
import { Route as DashitecnologyGoalsRouteImport } from './routes/dashitecnology/goals'
import { Route as DashitecnologyGamificationRouteImport } from './routes/dashitecnology/gamification'
import { Route as DashitecnologyContentRouteImport } from './routes/dashitecnology/content'
import { Route as DashitecnologyCheckinsRouteImport } from './routes/dashitecnology/checkins'
import { Route as DashitecnologyCharlieRouteImport } from './routes/dashitecnology/charlie'
import { Route as DashitecnologyAnalyticsRouteImport } from './routes/dashitecnology/analytics'
import { Route as DashitecnologyAgentRouteImport } from './routes/dashitecnology/agent'
import { Route as AuthenticatedStoreRouteImport } from './routes/_authenticated/store'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated/mentor'
import { Route as AuthenticatedJourneyRouteImport } from './routes/_authenticated/journey'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as DashitecnologyUsersIndexRouteImport } from './routes/dashitecnology/users.index'
import { Route as DashitecnologyUsersUserIdRouteImport } from './routes/dashitecnology/users.$userId'
import { Route as AuthenticatedExercisesSlugRouteImport } from './routes/_authenticated/exercises.$slug'

const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashitecnologyRouteRoute = DashitecnologyRouteRouteImport.update({
  id: '/dashitecnology',
  path: '/dashitecnology',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashitecnologyIndexRoute = DashitecnologyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyWallpapersRoute =
  DashitecnologyWallpapersRouteImport.update({
    id: '/wallpapers',
    path: '/wallpapers',
    getParentRoute: () => DashitecnologyRouteRoute,
  } as any)
const DashitecnologyUsersRoute = DashitecnologyUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyTokensRoute = DashitecnologyTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyTelegramRoute = DashitecnologyTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologySystemRoute = DashitecnologySystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyNotificationsRoute =
  DashitecnologyNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashitecnologyRouteRoute,
  } as any)
const DashitecnologyMlRoute = DashitecnologyMlRouteImport.update({
  id: '/ml',
  path: '/ml',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyMaintenanceRoute =
  DashitecnologyMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => DashitecnologyRouteRoute,
  } as any)
const DashitecnologyLevelsRoute = DashitecnologyLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyJobsRoute = DashitecnologyJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyHabitsRoute = DashitecnologyHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyGoalsRoute = DashitecnologyGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyGamificationRoute =
  DashitecnologyGamificationRouteImport.update({
    id: '/gamification',
    path: '/gamification',
    getParentRoute: () => DashitecnologyRouteRoute,
  } as any)
const DashitecnologyContentRoute = DashitecnologyContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyCheckinsRoute = DashitecnologyCheckinsRouteImport.update({
  id: '/checkins',
  path: '/checkins',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyCharlieRoute = DashitecnologyCharlieRouteImport.update({
  id: '/charlie',
  path: '/charlie',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyAnalyticsRoute = DashitecnologyAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const DashitecnologyAgentRoute = DashitecnologyAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => DashitecnologyRouteRoute,
} as any)
const AuthenticatedStoreRoute = AuthenticatedStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJourneyRoute = AuthenticatedJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DashitecnologyUsersIndexRoute =
  DashitecnologyUsersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashitecnologyUsersRoute,
  } as any)
const DashitecnologyUsersUserIdRoute =
  DashitecnologyUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => DashitecnologyUsersRoute,
  } as any)
const AuthenticatedExercisesSlugRoute =
  AuthenticatedExercisesSlugRouteImport.update({
    id: '/exercises/$slug',
    path: '/exercises/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashitecnology': typeof DashitecnologyRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/maintenance': typeof MaintenanceRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/store': typeof AuthenticatedStoreRoute
  '/dashitecnology/agent': typeof DashitecnologyAgentRoute
  '/dashitecnology/analytics': typeof DashitecnologyAnalyticsRoute
  '/dashitecnology/charlie': typeof DashitecnologyCharlieRoute
  '/dashitecnology/checkins': typeof DashitecnologyCheckinsRoute
  '/dashitecnology/content': typeof DashitecnologyContentRoute
  '/dashitecnology/gamification': typeof DashitecnologyGamificationRoute
  '/dashitecnology/goals': typeof DashitecnologyGoalsRoute
  '/dashitecnology/habits': typeof DashitecnologyHabitsRoute
  '/dashitecnology/jobs': typeof DashitecnologyJobsRoute
  '/dashitecnology/levels': typeof DashitecnologyLevelsRoute
  '/dashitecnology/maintenance': typeof DashitecnologyMaintenanceRoute
  '/dashitecnology/ml': typeof DashitecnologyMlRoute
  '/dashitecnology/notifications': typeof DashitecnologyNotificationsRoute
  '/dashitecnology/system': typeof DashitecnologySystemRoute
  '/dashitecnology/telegram': typeof DashitecnologyTelegramRoute
  '/dashitecnology/tokens': typeof DashitecnologyTokensRoute
  '/dashitecnology/users': typeof DashitecnologyUsersRouteWithChildren
  '/dashitecnology/wallpapers': typeof DashitecnologyWallpapersRoute
  '/dashitecnology/': typeof DashitecnologyIndexRoute
  '/exercises/$slug': typeof AuthenticatedExercisesSlugRoute
  '/dashitecnology/users/$userId': typeof DashitecnologyUsersUserIdRoute
  '/dashitecnology/users/': typeof DashitecnologyUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/maintenance': typeof MaintenanceRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/store': typeof AuthenticatedStoreRoute
  '/dashitecnology/agent': typeof DashitecnologyAgentRoute
  '/dashitecnology/analytics': typeof DashitecnologyAnalyticsRoute
  '/dashitecnology/charlie': typeof DashitecnologyCharlieRoute
  '/dashitecnology/checkins': typeof DashitecnologyCheckinsRoute
  '/dashitecnology/content': typeof DashitecnologyContentRoute
  '/dashitecnology/gamification': typeof DashitecnologyGamificationRoute
  '/dashitecnology/goals': typeof DashitecnologyGoalsRoute
  '/dashitecnology/habits': typeof DashitecnologyHabitsRoute
  '/dashitecnology/jobs': typeof DashitecnologyJobsRoute
  '/dashitecnology/levels': typeof DashitecnologyLevelsRoute
  '/dashitecnology/maintenance': typeof DashitecnologyMaintenanceRoute
  '/dashitecnology/ml': typeof DashitecnologyMlRoute
  '/dashitecnology/notifications': typeof DashitecnologyNotificationsRoute
  '/dashitecnology/system': typeof DashitecnologySystemRoute
  '/dashitecnology/telegram': typeof DashitecnologyTelegramRoute
  '/dashitecnology/tokens': typeof DashitecnologyTokensRoute
  '/dashitecnology/wallpapers': typeof DashitecnologyWallpapersRoute
  '/dashitecnology': typeof DashitecnologyIndexRoute
  '/exercises/$slug': typeof AuthenticatedExercisesSlugRoute
  '/dashitecnology/users/$userId': typeof DashitecnologyUsersUserIdRoute
  '/dashitecnology/users': typeof DashitecnologyUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/dashitecnology': typeof DashitecnologyRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/maintenance': typeof MaintenanceRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/journey': typeof AuthenticatedJourneyRoute
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/store': typeof AuthenticatedStoreRoute
  '/dashitecnology/agent': typeof DashitecnologyAgentRoute
  '/dashitecnology/analytics': typeof DashitecnologyAnalyticsRoute
  '/dashitecnology/charlie': typeof DashitecnologyCharlieRoute
  '/dashitecnology/checkins': typeof DashitecnologyCheckinsRoute
  '/dashitecnology/content': typeof DashitecnologyContentRoute
  '/dashitecnology/gamification': typeof DashitecnologyGamificationRoute
  '/dashitecnology/goals': typeof DashitecnologyGoalsRoute
  '/dashitecnology/habits': typeof DashitecnologyHabitsRoute
  '/dashitecnology/jobs': typeof DashitecnologyJobsRoute
  '/dashitecnology/levels': typeof DashitecnologyLevelsRoute
  '/dashitecnology/maintenance': typeof DashitecnologyMaintenanceRoute
  '/dashitecnology/ml': typeof DashitecnologyMlRoute
  '/dashitecnology/notifications': typeof DashitecnologyNotificationsRoute
  '/dashitecnology/system': typeof DashitecnologySystemRoute
  '/dashitecnology/telegram': typeof DashitecnologyTelegramRoute
  '/dashitecnology/tokens': typeof DashitecnologyTokensRoute
  '/dashitecnology/users': typeof DashitecnologyUsersRouteWithChildren
  '/dashitecnology/wallpapers': typeof DashitecnologyWallpapersRoute
  '/dashitecnology/': typeof DashitecnologyIndexRoute
  '/_authenticated/exercises/$slug': typeof AuthenticatedExercisesSlugRoute
  '/dashitecnology/users/$userId': typeof DashitecnologyUsersUserIdRoute
  '/dashitecnology/users/': typeof DashitecnologyUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashitecnology'
    | '/auth'
    | '/maintenance'
    | '/goals'
    | '/habits'
    | '/journey'
    | '/mentor'
    | '/onboarding'
    | '/profile'
    | '/store'
    | '/dashitecnology/agent'
    | '/dashitecnology/analytics'
    | '/dashitecnology/charlie'
    | '/dashitecnology/checkins'
    | '/dashitecnology/content'
    | '/dashitecnology/gamification'
    | '/dashitecnology/goals'
    | '/dashitecnology/habits'
    | '/dashitecnology/jobs'
    | '/dashitecnology/levels'
    | '/dashitecnology/maintenance'
    | '/dashitecnology/ml'
    | '/dashitecnology/notifications'
    | '/dashitecnology/system'
    | '/dashitecnology/telegram'
    | '/dashitecnology/tokens'
    | '/dashitecnology/users'
    | '/dashitecnology/wallpapers'
    | '/dashitecnology/'
    | '/exercises/$slug'
    | '/dashitecnology/users/$userId'
    | '/dashitecnology/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/maintenance'
    | '/goals'
    | '/habits'
    | '/journey'
    | '/mentor'
    | '/onboarding'
    | '/profile'
    | '/store'
    | '/dashitecnology/agent'
    | '/dashitecnology/analytics'
    | '/dashitecnology/charlie'
    | '/dashitecnology/checkins'
    | '/dashitecnology/content'
    | '/dashitecnology/gamification'
    | '/dashitecnology/goals'
    | '/dashitecnology/habits'
    | '/dashitecnology/jobs'
    | '/dashitecnology/levels'
    | '/dashitecnology/maintenance'
    | '/dashitecnology/ml'
    | '/dashitecnology/notifications'
    | '/dashitecnology/system'
    | '/dashitecnology/telegram'
    | '/dashitecnology/tokens'
    | '/dashitecnology/wallpapers'
    | '/dashitecnology'
    | '/exercises/$slug'
    | '/dashitecnology/users/$userId'
    | '/dashitecnology/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/dashitecnology'
    | '/auth'
    | '/maintenance'
    | '/_authenticated/goals'
    | '/_authenticated/habits'
    | '/_authenticated/journey'
    | '/_authenticated/mentor'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/store'
    | '/dashitecnology/agent'
    | '/dashitecnology/analytics'
    | '/dashitecnology/charlie'
    | '/dashitecnology/checkins'
    | '/dashitecnology/content'
    | '/dashitecnology/gamification'
    | '/dashitecnology/goals'
    | '/dashitecnology/habits'
    | '/dashitecnology/jobs'
    | '/dashitecnology/levels'
    | '/dashitecnology/maintenance'
    | '/dashitecnology/ml'
    | '/dashitecnology/notifications'
    | '/dashitecnology/system'
    | '/dashitecnology/telegram'
    | '/dashitecnology/tokens'
    | '/dashitecnology/users'
    | '/dashitecnology/wallpapers'
    | '/dashitecnology/'
    | '/_authenticated/exercises/$slug'
    | '/dashitecnology/users/$userId'
    | '/dashitecnology/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DashitecnologyRouteRoute: typeof DashitecnologyRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MaintenanceRoute: typeof MaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashitecnology': {
      id: '/dashitecnology'
      path: '/dashitecnology'
      fullPath: '/dashitecnology'
      preLoaderRoute: typeof DashitecnologyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashitecnology/': {
      id: '/dashitecnology/'
      path: '/'
      fullPath: '/dashitecnology/'
      preLoaderRoute: typeof DashitecnologyIndexRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/wallpapers': {
      id: '/dashitecnology/wallpapers'
      path: '/wallpapers'
      fullPath: '/dashitecnology/wallpapers'
      preLoaderRoute: typeof DashitecnologyWallpapersRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/users': {
      id: '/dashitecnology/users'
      path: '/users'
      fullPath: '/dashitecnology/users'
      preLoaderRoute: typeof DashitecnologyUsersRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/tokens': {
      id: '/dashitecnology/tokens'
      path: '/tokens'
      fullPath: '/dashitecnology/tokens'
      preLoaderRoute: typeof DashitecnologyTokensRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/telegram': {
      id: '/dashitecnology/telegram'
      path: '/telegram'
      fullPath: '/dashitecnology/telegram'
      preLoaderRoute: typeof DashitecnologyTelegramRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/system': {
      id: '/dashitecnology/system'
      path: '/system'
      fullPath: '/dashitecnology/system'
      preLoaderRoute: typeof DashitecnologySystemRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/notifications': {
      id: '/dashitecnology/notifications'
      path: '/notifications'
      fullPath: '/dashitecnology/notifications'
      preLoaderRoute: typeof DashitecnologyNotificationsRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/ml': {
      id: '/dashitecnology/ml'
      path: '/ml'
      fullPath: '/dashitecnology/ml'
      preLoaderRoute: typeof DashitecnologyMlRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/maintenance': {
      id: '/dashitecnology/maintenance'
      path: '/maintenance'
      fullPath: '/dashitecnology/maintenance'
      preLoaderRoute: typeof DashitecnologyMaintenanceRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/levels': {
      id: '/dashitecnology/levels'
      path: '/levels'
      fullPath: '/dashitecnology/levels'
      preLoaderRoute: typeof DashitecnologyLevelsRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/jobs': {
      id: '/dashitecnology/jobs'
      path: '/jobs'
      fullPath: '/dashitecnology/jobs'
      preLoaderRoute: typeof DashitecnologyJobsRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/habits': {
      id: '/dashitecnology/habits'
      path: '/habits'
      fullPath: '/dashitecnology/habits'
      preLoaderRoute: typeof DashitecnologyHabitsRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/goals': {
      id: '/dashitecnology/goals'
      path: '/goals'
      fullPath: '/dashitecnology/goals'
      preLoaderRoute: typeof DashitecnologyGoalsRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/gamification': {
      id: '/dashitecnology/gamification'
      path: '/gamification'
      fullPath: '/dashitecnology/gamification'
      preLoaderRoute: typeof DashitecnologyGamificationRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/content': {
      id: '/dashitecnology/content'
      path: '/content'
      fullPath: '/dashitecnology/content'
      preLoaderRoute: typeof DashitecnologyContentRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/checkins': {
      id: '/dashitecnology/checkins'
      path: '/checkins'
      fullPath: '/dashitecnology/checkins'
      preLoaderRoute: typeof DashitecnologyCheckinsRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/charlie': {
      id: '/dashitecnology/charlie'
      path: '/charlie'
      fullPath: '/dashitecnology/charlie'
      preLoaderRoute: typeof DashitecnologyCharlieRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/analytics': {
      id: '/dashitecnology/analytics'
      path: '/analytics'
      fullPath: '/dashitecnology/analytics'
      preLoaderRoute: typeof DashitecnologyAnalyticsRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/dashitecnology/agent': {
      id: '/dashitecnology/agent'
      path: '/agent'
      fullPath: '/dashitecnology/agent'
      preLoaderRoute: typeof DashitecnologyAgentRouteImport
      parentRoute: typeof DashitecnologyRouteRoute
    }
    '/_authenticated/store': {
      id: '/_authenticated/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AuthenticatedStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journey': {
      id: '/_authenticated/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AuthenticatedJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/dashitecnology/users/': {
      id: '/dashitecnology/users/'
      path: '/'
      fullPath: '/dashitecnology/users/'
      preLoaderRoute: typeof DashitecnologyUsersIndexRouteImport
      parentRoute: typeof DashitecnologyUsersRoute
    }
    '/dashitecnology/users/$userId': {
      id: '/dashitecnology/users/$userId'
      path: '/$userId'
      fullPath: '/dashitecnology/users/$userId'
      preLoaderRoute: typeof DashitecnologyUsersUserIdRouteImport
      parentRoute: typeof DashitecnologyUsersRoute
    }
    '/_authenticated/exercises/$slug': {
      id: '/_authenticated/exercises/$slug'
      path: '/exercises/$slug'
      fullPath: '/exercises/$slug'
      preLoaderRoute: typeof AuthenticatedExercisesSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedJourneyRoute: typeof AuthenticatedJourneyRoute
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStoreRoute: typeof AuthenticatedStoreRoute
  AuthenticatedExercisesSlugRoute: typeof AuthenticatedExercisesSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedJourneyRoute: AuthenticatedJourneyRoute,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStoreRoute: AuthenticatedStoreRoute,
  AuthenticatedExercisesSlugRoute: AuthenticatedExercisesSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DashitecnologyUsersRouteChildren {
  DashitecnologyUsersUserIdRoute: typeof DashitecnologyUsersUserIdRoute
  DashitecnologyUsersIndexRoute: typeof DashitecnologyUsersIndexRoute
}

const DashitecnologyUsersRouteChildren: DashitecnologyUsersRouteChildren = {
  DashitecnologyUsersUserIdRoute: DashitecnologyUsersUserIdRoute,
  DashitecnologyUsersIndexRoute: DashitecnologyUsersIndexRoute,
}

const DashitecnologyUsersRouteWithChildren =
  DashitecnologyUsersRoute._addFileChildren(DashitecnologyUsersRouteChildren)

interface DashitecnologyRouteRouteChildren {
  DashitecnologyAgentRoute: typeof DashitecnologyAgentRoute
  DashitecnologyAnalyticsRoute: typeof DashitecnologyAnalyticsRoute
  DashitecnologyCharlieRoute: typeof DashitecnologyCharlieRoute
  DashitecnologyCheckinsRoute: typeof DashitecnologyCheckinsRoute
  DashitecnologyContentRoute: typeof DashitecnologyContentRoute
  DashitecnologyGamificationRoute: typeof DashitecnologyGamificationRoute
  DashitecnologyGoalsRoute: typeof DashitecnologyGoalsRoute
  DashitecnologyHabitsRoute: typeof DashitecnologyHabitsRoute
  DashitecnologyJobsRoute: typeof DashitecnologyJobsRoute
  DashitecnologyLevelsRoute: typeof DashitecnologyLevelsRoute
  DashitecnologyMaintenanceRoute: typeof DashitecnologyMaintenanceRoute
  DashitecnologyMlRoute: typeof DashitecnologyMlRoute
  DashitecnologyNotificationsRoute: typeof DashitecnologyNotificationsRoute
  DashitecnologySystemRoute: typeof DashitecnologySystemRoute
  DashitecnologyTelegramRoute: typeof DashitecnologyTelegramRoute
  DashitecnologyTokensRoute: typeof DashitecnologyTokensRoute
  DashitecnologyUsersRoute: typeof DashitecnologyUsersRouteWithChildren
  DashitecnologyWallpapersRoute: typeof DashitecnologyWallpapersRoute
  DashitecnologyIndexRoute: typeof DashitecnologyIndexRoute
}

const DashitecnologyRouteRouteChildren: DashitecnologyRouteRouteChildren = {
  DashitecnologyAgentRoute: DashitecnologyAgentRoute,
  DashitecnologyAnalyticsRoute: DashitecnologyAnalyticsRoute,
  DashitecnologyCharlieRoute: DashitecnologyCharlieRoute,
  DashitecnologyCheckinsRoute: DashitecnologyCheckinsRoute,
  DashitecnologyContentRoute: DashitecnologyContentRoute,
  DashitecnologyGamificationRoute: DashitecnologyGamificationRoute,
  DashitecnologyGoalsRoute: DashitecnologyGoalsRoute,
  DashitecnologyHabitsRoute: DashitecnologyHabitsRoute,
  DashitecnologyJobsRoute: DashitecnologyJobsRoute,
  DashitecnologyLevelsRoute: DashitecnologyLevelsRoute,
  DashitecnologyMaintenanceRoute: DashitecnologyMaintenanceRoute,
  DashitecnologyMlRoute: DashitecnologyMlRoute,
  DashitecnologyNotificationsRoute: DashitecnologyNotificationsRoute,
  DashitecnologySystemRoute: DashitecnologySystemRoute,
  DashitecnologyTelegramRoute: DashitecnologyTelegramRoute,
  DashitecnologyTokensRoute: DashitecnologyTokensRoute,
  DashitecnologyUsersRoute: DashitecnologyUsersRouteWithChildren,
  DashitecnologyWallpapersRoute: DashitecnologyWallpapersRoute,
  DashitecnologyIndexRoute: DashitecnologyIndexRoute,
}

const DashitecnologyRouteRouteWithChildren =
  DashitecnologyRouteRoute._addFileChildren(DashitecnologyRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DashitecnologyRouteRoute: DashitecnologyRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MaintenanceRoute: MaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
